plugins {
	id 'fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
}

loom {
	accessWidenerPath = file("src/main/resources/physex.accesswidener")
	mixin {
		useLegacyMixinAp = true
		defaultRefmapName = "physex-refmap.json"
	}
}

allprojects {
	apply plugin: 'java'
	apply plugin: 'idea'
	repositories {
		mavenCentral()
	}
	dependencies {
		compileOnly 'org.projectlombok:lombok:1.18.40'
		annotationProcessor 'org.projectlombok:lombok:1.18.40'
		testCompileOnly 'org.projectlombok:lombok:1.18.40'
		testAnnotationProcessor 'org.projectlombok:lombok:1.18.40'
	}

	java {
		sourceCompatibility = JavaVersion.VERSION_21
		targetCompatibility = JavaVersion.VERSION_21
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	implementation project(':skdslib')
	include project(':skdslib')
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

project(":skdslib") {
	sourceSets {
		List<String> excludes = List.of(
				"net/skds/lib2/natives/**",
				"net/skds/lib2/shapes/**",
				"net/skds/lib2/shapes2d/**",
				"net/skds/lib2/physics2d/**",
				"net/skds/lib2/shapes2d/Demo2D.java",
				"net/skds/lib2/demo/**",
				"net/skds/lib2/security/**",
				"net/skds/lib2/network/**",
				"net/skds/lib2/misc/noise/**",
				"net/skds/lib2/utils/platforms/**",
				"net/skds/tests/**",
				"net/skds/lib2/utils/ThreadAnalyzer.java"
		)

		main {
			java {
				exclude excludes
			}
		}
		test {
			java {
				exclude excludes
			}
		}
	}
}
