plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'com.gradleup.shadow' version '9.2.2'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

configurations {
	libs

	compileClasspath.extendsFrom libs
	runtimeClasspath.extendsFrom libs
}

loom {
	accessWidenerPath = file("src/main/resources/physex.accesswidener")
}

allprojects {
	apply plugin: 'java'
	apply plugin: 'idea'
	repositories {
		mavenCentral()
	}
	dependencies {
		compileOnly 'org.projectlombok:lombok:1.18.40'
		annotationProcessor 'org.projectlombok:lombok:1.18.40'
		testCompileOnly 'org.projectlombok:lombok:1.18.40'
		testAnnotationProcessor 'org.projectlombok:lombok:1.18.40'
	}

	//tasks.withType(JavaCompile).configureEach {
	//    it.options.release = 21
	//    it.options.re = 25
	//}
	java {
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

	libs(project(':skdslib'))
}


shadowJar {
	configurations = [project.configurations.libs]
	archiveClassifier = 'dev-shadow'
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

